TRAINING_RAW_DIR = r"artifacts/training/raw"
TRAINING_CLEANED_DIR = r"artifacts/training/cleaned"
TRAINING_FILTERED_DIR = r"artifacts/training/filtered"
TRAINING_FEATURES_DIR = r"artifacts/training/features"
TRAINING_CLUSTERS_DIR = r"artifacts/training/clusters"
TRAINING_MODELS_DIR = r"artifacts/training/models"

INFERENCE_RAW_DIR = r"artifacts/inference/raw"
INFERENCE_CLEANED_DIR = r"artifacts/inference/cleaned"
INFERENCE_FILTERED_DIR = r"artifacts/inference/filtered"
INFERENCE_FEATURES_DIR = r"artifacts/inference/features"

CHIPSHOT_CLUSTER_DIR = r"artifacts/training/clusters/chipshot"
CURVE_CLUSTER_DIR = r"artifacts/training/clusters/curve"
LONGPASS_CLUSTER_DIR = r"artifacts/training/curve/longpass"
POWERSHOT_CLUSTER_DIR = r"artifacts/training/clusters/powershot"
SHORTPASS_CLUSTER_DIR = r"artifacts/training/clusters/shortpass"
TRIVELA_CLUSTER_DIR = r"artifacts/training/clusters/trivela"
VOLLEY_CLUSTER_DIR = r"artifacts/training/clusters/volley"

CHIPSHOT_MODEL_DIR = r"artifacts/training/models/chipshot"
CURVE_MODEL_DIR = r"artifacts/training/models/curve"
LONGPASS_MODEL_DIR = r"artifacts/training/curve/longpass"
POWERSHOT_MODEL_DIR = r"artifacts/training/models/powershot"
SHORTPASS_MODEL_DIR = r"artifacts/training/models/shortpass"
TRIVELA_MODEL_DIR = r"artifacts/training/models/trivela"
VOLLEY_MODEL_DIR = r"artifacts/training/models/volley"